---
name: java ci cd maven  
on:
    pull_request:
      branches:
        - main
    workflow_dispatch: #manual trigger

permissions:
    contents: read
    id-token: write
    pull-requests: write
jobs:
    maven:
        runs-on: [ 'ubuntu-latest' ]
        strategy:
          matrix:
            java: [ '21', '17' ]
        steps:
           - uses: actions/checkout@v5
           - uses: actions/setup-java@v5
             with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '21'
              cache: 'maven'
           - name: goal variables
             run: mvn ${{ vars.GOAL }}
           - name: publish test results
             uses: EnricoMi/publish-unit-test-result-action@v2
             with:
               files: |
                 **/target/surefire-reports/*.xml
           - name: Uploading packaged jar files
             uses: actions/upload-artifact@v4
             with:
               name: spring-petclinic-${{ matrix.java }}.jar
               path: '**/target/*.jar'